In [2]:
import torch
print(torch.__version__)

2.0.1


## Tensors

### Creating tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([1, 2, 3, 4])
print("vector: ", vector, "\nndim: ", vector.ndim, "\nshape: ", vector.shape)

vector:  tensor([1, 2, 3, 4]) 
ndim:  1 
shape:  torch.Size([4])


In [7]:
matrix = torch.tensor([[1, 2], [9, 10]])
print("Matrix: ", matrix, "\nDimension: ", matrix.ndim, "\nShape: ", matrix.shape)

Matrix:  tensor([[ 1,  2],
        [ 9, 10]]) 
Dimension:  2 
Shape:  torch.Size([2, 2])


In [8]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Tensor: ", tensor, "\n Dimension: ", tensor.ndim, "\n Shape: ", tensor.shape)


Tensor:  tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) 
 Dimension:  3 
 Shape:  torch.Size([2, 2, 3])


## Random Tensors

Needed for initialization of weights in neural networks

In [9]:
random_tensor = torch.rand(3, 3, 3)
print("Random Tensor: ", random_tensor, "\n Dimension: ", random_tensor.ndim, "\n Shape: ", random_tensor.shape)

Random Tensor:  tensor([[[0.7505, 0.6709, 0.3263],
         [0.4734, 0.6222, 0.9941],
         [0.9950, 0.3688, 0.0681]],

        [[0.5033, 0.6186, 0.5128],
         [0.6268, 0.5221, 0.6751],
         [0.0896, 0.4731, 0.7830]],

        [[0.2730, 0.2532, 0.4285],
         [0.9679, 0.4501, 0.9996],
         [0.8308, 0.0059, 0.7266]]]) 
 Dimension:  3 
 Shape:  torch.Size([3, 3, 3])


In [10]:
rand_img_tensor = torch.rand(224, 224, 3) # height, width, color
print("Random Image Tensor: ", rand_img_tensor, "\n Dimension: ", rand_img_tensor.ndim, "\n Shape: ", rand_img_tensor.shape)

Random Image Tensor:  tensor([[[5.6605e-01, 1.9975e-01, 9.2985e-02],
         [3.9671e-01, 1.1254e-01, 1.3358e-01],
         [5.8193e-01, 9.4234e-01, 5.5391e-02],
         ...,
         [4.2774e-01, 7.6335e-01, 7.8217e-01],
         [2.2612e-01, 1.9239e-01, 2.2320e-01],
         [5.5931e-01, 3.1243e-01, 3.7185e-01]],

        [[9.7981e-02, 6.2386e-01, 8.7803e-01],
         [8.9053e-01, 9.2129e-01, 9.9839e-01],
         [3.0498e-01, 2.4918e-01, 5.7168e-01],
         ...,
         [3.7173e-01, 2.2893e-01, 7.8920e-01],
         [4.3715e-01, 6.6050e-01, 1.4411e-02],
         [2.5710e-02, 4.1674e-01, 9.9625e-01]],

        [[2.6025e-01, 1.8722e-01, 2.7636e-01],
         [8.5328e-01, 8.4587e-01, 3.4849e-01],
         [1.1674e-01, 7.7753e-02, 7.1434e-01],
         ...,
         [6.8690e-01, 1.1793e-01, 6.4569e-01],
         [1.9211e-01, 8.4673e-01, 9.1186e-01],
         [8.5368e-01, 4.5310e-02, 1.2512e-01]],

        ...,

        [[5.0829e-01, 1.4012e-01, 8.4750e-01],
         [4.6310e-02, 4

## Zero and Ones Tensors

In [11]:
ones = torch.ones(3, 3)
print("Ones: ", ones, "\n Dimension: ", ones.ndim, "\n Shape: ", ones.shape)

zeros = torch.zeros(3, 3)
print("Zeros: ", zeros, "\n Dimension: ", zeros.ndim, "\n Shape: ", zeros.shape)

Ones:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 
 Dimension:  2 
 Shape:  torch.Size([3, 3])
Zeros:  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 Dimension:  2 
 Shape:  torch.Size([3, 3])


## Range Tensors

In [12]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

## Tensor Manipulation

In [13]:
tensor = torch.tensor([1, 2, 3])
tensor *= 5
tensor

tensor([ 5, 10, 15])

### Element-wise operations

In [16]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix *= tensor
matrix

tensor([[ 5, 20, 45],
        [20, 50, 90]])

### Matrix multiplication

In [20]:
torch.matmul(matrix, matrix.T)

tensor([[ 2450,  5150],
        [ 5150, 11000]])

## Tensor Aggregation

In [21]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
tensor.shape

torch.Size([2, 2, 3])

In [24]:
tensor.max(), tensor.min()

(tensor(12), tensor(1))

In [27]:
float_tensor = tensor.to(dtype=torch.float32)

In [29]:
float_tensor.mean(), float_tensor.std()

(tensor(6.5000), tensor(3.6056))

In [30]:
tensor.argmin(), tensor.argmax()

(tensor(0),
 tensor(11),
 tensor([[[0, 1, 2],
          [0, 1, 2]],
 
         [[0, 1, 2],
          [0, 1, 2]]]))

## Reshaping, stacking, squeezing and unsqueezing tensors

reshape - change the shape of a tensor (number of elements stays the same)

stacking - join a sequence of tensors along a new dimension

squeezing - remove a dimension with length 1

unsqueezing - add a dimension with length 1


In [37]:
x = torch.arange(1.0, 11.0, 1)

In [38]:
x_reshaped = x.reshape(5, 2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [44]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [45]:
x = torch.rand(1,1,3)
x

tensor([[[0.9942, 0.0894, 0.7334]]])

In [46]:
x_sqeezed = x.squeeze()
x_sqeezed

tensor([0.9942, 0.0894, 0.7334])

In [51]:
x_unsqeezed = x_sqeezed.unsqueeze(dim=0)
x_unsqeezed

tensor([[0.9942, 0.0894, 0.7334]])

In [56]:
x = torch.rand(224, 224, 3)
x

tensor([[[0.8066, 0.8050, 0.9923],
         [0.7133, 0.3018, 0.1959],
         [0.0554, 0.1894, 0.7721],
         ...,
         [0.4685, 0.4291, 0.6156],
         [0.4242, 0.7929, 0.4063],
         [0.2039, 0.4165, 0.1520]],

        [[0.6067, 0.4839, 0.3060],
         [0.3961, 0.2042, 0.6338],
         [0.2026, 0.8040, 0.9762],
         ...,
         [0.1036, 0.8428, 0.3450],
         [0.5016, 0.7886, 0.3189],
         [0.2864, 0.4448, 0.7672]],

        [[0.4432, 0.1089, 0.2597],
         [0.1809, 0.4124, 0.9989],
         [0.2772, 0.8246, 0.5829],
         ...,
         [0.8374, 0.9619, 0.8303],
         [0.9816, 0.6584, 0.6713],
         [0.2438, 0.9184, 0.2153]],

        ...,

        [[0.5670, 0.4340, 0.8811],
         [0.5608, 0.6164, 0.2160],
         [0.2015, 0.0413, 0.8299],
         ...,
         [0.9115, 0.5703, 0.4859],
         [0.3465, 0.7428, 0.2214],
         [0.8578, 0.1080, 0.8657]],

        [[0.4720, 0.5054, 0.5255],
         [0.4352, 0.3813, 0.1708],
         [0.

In [57]:
x_permuted = x.permute(2, 0, 1)
x

tensor([[[0.8066, 0.8050, 0.9923],
         [0.7133, 0.3018, 0.1959],
         [0.0554, 0.1894, 0.7721],
         ...,
         [0.4685, 0.4291, 0.6156],
         [0.4242, 0.7929, 0.4063],
         [0.2039, 0.4165, 0.1520]],

        [[0.6067, 0.4839, 0.3060],
         [0.3961, 0.2042, 0.6338],
         [0.2026, 0.8040, 0.9762],
         ...,
         [0.1036, 0.8428, 0.3450],
         [0.5016, 0.7886, 0.3189],
         [0.2864, 0.4448, 0.7672]],

        [[0.4432, 0.1089, 0.2597],
         [0.1809, 0.4124, 0.9989],
         [0.2772, 0.8246, 0.5829],
         ...,
         [0.8374, 0.9619, 0.8303],
         [0.9816, 0.6584, 0.6713],
         [0.2438, 0.9184, 0.2153]],

        ...,

        [[0.5670, 0.4340, 0.8811],
         [0.5608, 0.6164, 0.2160],
         [0.2015, 0.0413, 0.8299],
         ...,
         [0.9115, 0.5703, 0.4859],
         [0.3465, 0.7428, 0.2214],
         [0.8578, 0.1080, 0.8657]],

        [[0.4720, 0.5054, 0.5255],
         [0.4352, 0.3813, 0.1708],
         [0.

## NumPy and PyTorch interoperability

In [59]:
import numpy as np
np_array = np.arange(0, 10, 1).reshape(5, 2)
tensor = torch.from_numpy(np_array)
np_array, tensor

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))